# Generated by Django 4.0.2 on 2022-02-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_image',
            field=models.FileField(null=True, upload_to='productimgs'),
        ),
    ]
